### PR TITLE
Try and associate a pull policy when we know its a floating tag.

### LINKED ISSUE #421: TestcontainersKafkaCluster may use stale latest kafka images
**Describe the bug**

quay.io/ogunalp/kafka-native's [tagging container scheme](https://quay.io/repository/ogunalp/kafka-native?tab=tags&tag=latest) includes the use of latest floating tags:

* `latest` means the latest image for the latest kafka release known to kafka-native
* `latest-snapshot` mean the latest snapshot created by ogunalp's CI
* `latest-kafka-3.9.0` means the  latest image release supporting Kafka 3.9.0

Kroxylicious Junit Ext defaults to using the latter (`latest-kafka-x.y.z`) with x.y.z based on the version of Kafka in the classpath.  It is possible for the user of the Junit Ext to override this behaviour.

The issue is that the image `latest-kafka-x.x.x` in the user's Docker/Podman cache might be stale.  The Junit Ext does not specify a pull policy, so the Testcontainer defaults are applying.   The upshot is that the the user's code runs with an unexpected image.

We should consider telling Docker to use a Always pull policy when using floating tags such as latest.

**Expected behavior**

**Logs**

Attach or copy and paste relevant logs.

**Additional context**

We might consider doing something like:

```
        KafkaContainer kafkaContainer = new KafkaContainer(kafkaImage)
                .withName(name)
                .withNetwork(network)
                .withImagePullPolicy(kafkaImage.getVersionPart().contains("latest") ? PullPolicy.alwaysPull() : null)
                .withNetworkAliases(netAlias);
```

### PR DESCRIPTION
**Pull request by SamBarker**
### Type of change

- Bugfix

### Description

Fixes #421 

### Additional Context

We should default to pull always when we know we are specifying a floating tag.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

File: impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+        final TestcontainersKafkaCluster.PerImagePullPolicy kafkaImage;
+        try (TestcontainersKafkaCluster testcontainersKafkaCluster = new TestcontainersKafkaCluster(DockerImageName.parse("quay.io/ogunalp/kafka-native:latest"), null, config)) {
+
+            // When
+            kafkaImage = testcontainersKafkaCluster.getKafkaImage();
+
+            // Then
+            assertThat(kafkaImage).isNotNull().satisfies(perImagePullPolicy -> {
+                assertThat(perImagePullPolicy.dockerImageName().getVersionPart()).startsWith("latest"); // TODO I think this should be equalTo but `overrideContainerImageTagIfNecessary` checks if the override is a number I suspect thats a bug...
+                final ImagePullPolicy actualPullPolicy = perImagePullPolicy.pullPolicy();
```
Comment (SamBarker) [inline impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java:50]: PR is still in draft as I haven't decided what the right behaviour for this test is.

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java [hunk 2]
```diff
@@ -290,17 +300,17 @@ private synchronized String buildBrokerList(Function<Integer, KafkaClusterConfig
      * @param overrideVersion desired version, which may be null.
      * @return container image name
      */
-    private DockerImageName overrideContainerImageTagIfNecessary(@NonNull DockerImageName image, @Nullable String overrideVersion) {
+    private PerImagePullPolicy overrideContainerImageTagIfNecessary(@NonNull DockerImageName image, @Nullable String overrideVersion) {
         if (overrideVersion == null || overrideVersion.equalsIgnoreCase(image.getVersionPart())) {
```
Comment (k-wall) [inline impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:304]: I wonder if we should allow the behaviour to be overridden by an env var in order to support use-cases such as disconnected developer environments.

Comment (SamBarker) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:304]: I'm inclined to agree, not sure here is the point to do so but I think the idea is good

Comment (SamBarker) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:304]: We support loading from ENV Vars a few levels higher see https://github.com/kroxylicious/kroxylicious-junit5-extension/blob/0822c5f5b096b1feee58b2170bcedf100f466e8d/impl/src/main/java/io/kroxylicious/testing/kafka/common/KafkaClusterFactory.java#L86-L91 

But those then get overridden by https://github.com/kroxylicious/kroxylicious-junit5-extension/blob/00b40bc9e436cdc119bd0948c2077a9781717314/impl/src/main/java/io/kroxylicious/testing/kafka/common/KafkaClusterConfig.java#L96-L104 which seems the wrong way round to me. 

I'm going to try and rationalise things a bit. 

@franvila can you remind me what we were trying to support when adding the env vars? As I want to make sure we still support that need.

Comment (franvila) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:304]: Passing Kafka/Zookeeper repo by env vars allows the user to pass whatever kafka image different from default kafka/zookeeper-native from Ozan Gunalp repo or using an older version from of those default images. 

If so, those images are passed to `TestcontainersKafkaCluster`.

TBH I don't recall why this method was added, but I found the [commit](https://github.com/franvila/kroxylicious-junit5-extension/commit/0822c5f5b096b1feee58b2170bcedf100f466e8d) done by @k-wall

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java [hunk 3]
```diff
@@ -184,11 +183,14 @@ public TestcontainersKafkaCluster(DockerImageName kafkaImage, DockerImageName zo
             this.zookeeper = null;
         }
         else {
-            this.zookeeper = new ZookeeperContainer(this.zookeeperImage)
+            var actualZookeeperImage = Optional.ofNullable(zookeeperImage).orElse(LATEST_ZOOKEEPER_IMAGE);
+            PerImagePullPolicy zookeeperImage1 = overrideContainerImageTagIfNecessary(actualZookeeperImage, clusterConfig.getKafkaVersion());
```
Comment (k-wall) [inline impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:187]: variable naming.
```suggestion
            PerImagePullPolicy zookeeperImagePullPolicy = overrideContainerImageTagIfNecessary(actualZookeeperImage, clusterConfig.getKafkaVersion());
```

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java (hunk 2 above)
Comment (k-wall) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:304]: The use-case it supports is the testing with kafka-native builds from alternative repos (other than `quay.io/ogunalp/kafka-native`).   I use this mechanism when I am making changes in kafka-native that I want to try out with the Junit Ext before they are merged to kafka-native.

Comment (k-wall) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:304]: It would probably make more sense if those image override env vars were a concern of TestcontainersKafkaCluster rather than the KafkaClusterFactory.    They should just override the images that would already be used.

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java [hunk 4]
```diff
@@ -837,4 +847,6 @@ private String buildScramUsersEnvVar() {
                 .collect(Collectors.joining(";"));
     }
 
+    record PerImagePullPolicy(DockerImageName dockerImageName, ImagePullPolicy pullPolicy) {
```
Comment (k-wall) [inline impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:850]: PerImagePullPolicy is not a good name.  `ImageWithPullPolicy` might be better.

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java (hunk 2 above)
Comment (SamBarker) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:304]: FFS I did that but apparently its not pushed up. 😱

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java [hunk 5]
```diff
@@ -290,17 +300,17 @@ private synchronized String buildBrokerList(Function<Integer, KafkaClusterConfig
      * @param overrideVersion desired version, which may be null.
      * @return container image name
      */
-    private DockerImageName overrideContainerImageTagIfNecessary(@NonNull DockerImageName image, @Nullable String overrideVersion) {
```
[the remark this answers is not in the document]
Comment (SamBarker) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:293]: I've pushed things down into this method.

[the remark this answers is not in the document]
Comment (SamBarker) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:293]: Or rather what was this method.

File: impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java [hunk 6]
```diff
@@ -0,0 +1,256 @@
...
+
+            // When
+            final TestcontainersKafkaCluster.PerImagePullPolicy kafkaImage = testcontainersKafkaCluster.getKafkaImage();
+
+            // Then
+            assertThat(kafkaImage)
+                    .isNotNull().satisfies(perImagePullPolicy -> {
+                        assertThat(perImagePullPolicy.dockerImageName().getVersionPart()).isEqualTo("latest-kafka-" + version.value());
+                        final ImagePullPolicy actualPullPolicy = perImagePullPolicy.pullPolicy();
+                        assertThat(actualPullPolicy).isInstanceOf(ImagePullPolicy.class); // We can't see `AlwaysPullPolicy` as it's not public
```
Comment (SamBarker) [inline impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java:133]: Hmm not convinced this should actually be this policy. Its not strictly part of this test either.

File: pom.xml [hunk 7]
```diff
@@ -378,6 +382,10 @@
                         <systemPropertyVariables>
                             <container.logs.dir>${project.build.directory}/container-logs/</container.logs.dir>
                         </systemPropertyVariables>
+                        <argLine>
+                            --add-opens java.base/java.util=ALL-UNNAMED
```
Comment (SamBarker) [inline pom.xml:386]: Required so we can use junit-pioneer to mess with env vars.

**Review by SamBarker — COMMENTED** [review]
I'm seeing test failures locally because `kafka-native:latest` has moved to Kafka 3.9.0 😢 

Not sure how to handle that.

```
2024-11-21 12:19:49 ERROR tc.quay.io/ogunalp/kafka-native:latest:549 - Log output from the failed container:
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-11-20 23:19:06,290 ERROR [io.qua.run.Application] (main) Failed to start application: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:121)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: requirement failed: advertised.listeners cannot use the nonroutable meta-address 0.0.0.0. Use a routable IP address.
	at scala.Predef$.require(Predef.scala:337)
	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1022)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:852)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:185)
	at kafka.server.KafkaConfig.fromProps(KafkaConfig.scala:101)
	at com.ozangunalp.kafka.server.EmbeddedKafkaBroker.start(EmbeddedKafkaBroker.java:216)
	at com.ozangunalp.kafka.server.Startup.startup(Startup.java:38)
	at com.ozangunalp.kafka.server.Startup_Observer_startup_lDxI_XYb49w9c3LH146P8PmORkk.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:163)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:114)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 7 more
```

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java [hunk 8]
```diff
@@ -115,8 +129,8 @@ public class TestcontainersKafkaCluster implements Startable, KafkaCluster, Kafk
     // This uid needs to match the uid used by the kafka container to execute the kafka process
     private static final String KAFKA_CONTAINER_UID = "1001";
     private static final int READY_TIMEOUT_SECONDS = 120;
-    private final DockerImageName kafkaImage;
-    private final DockerImageName zookeeperImage;
+    public static final String MAJOR_MINOR_PATCH = "\\d+(\\.\\d+(\\.\\d+)?)?";
```
Comment (k-wall) [inline impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:132]: Precompile the RE

Comment (SamBarker) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:132]: Doh good point.

File: pom.xml [hunk 9]
```diff
@@ -241,6 +239,12 @@
                 <artifactId>moby-names-generator</artifactId>
                 <version>${moby-names-generator.version}</version>
             </dependency>
+            <dependency>
+                <groupId>org.junit-pioneer</groupId>
+                <artifactId>junit-pioneer</artifactId>
+                <version>2.3.0</version>
```
Comment (k-wall) [inline pom.xml:245]: extract a variable for this.

File: impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java (hunk 6 above)
Comment (k-wall) [reply impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java:133]: It serves to document that you wish to assert that an always pull policy is in place, but you cannot because of the protection policy.   I'd have made the test assert the policy's class name (ugly/fragile though that is).

Comment (k-wall) [reply impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java:133]: Did you see my suggestion to implement our own ImagePullPolicy.  We'd implement the class to give always behaviour for tags that start latest and default otherwise.   It would be cinch to unit test too.

Comment (SamBarker) [reply impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java:133]: I had but I hadn't realised the implications that is probably a good move. 

I think this PR then just becomes about sorting the image selection so it all happens in one testable place.

**Comment by k-wall** [comment]
I verified that with your refactoring on this PR, `KAFKA_IMAGE_REPO`/`KAFKA_IMAGE_TAG` env vars can still be used to direct TestContainersKafkaCluster to an alternative image registry/organisation.

File: impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java [hunk 10]
```diff
@@ -0,0 +1,256 @@
...
+                        assertThat(actualPullPolicy.shouldPull(perImagePullPolicy.dockerImageName())).isTrue();
+                    });
+        }
+    }
+
+    private static Stream<Version> fixedVersions() {
+        return Stream.of(
+                version("3.6.0"),
```
Comment (k-wall) [inline impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java:161]: Is there a reason to stop at 3.6.0?

Comment (SamBarker) [reply impl/src/test/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaClusterTest.java:161]: It's the same set as the TemplateTest which tries to actually fire things up (this test was written as that was failing and hard to debug).

I'm not sure the set of versions actually matters but while we are talking about it I'll add the missing versions.

**Comment by k-wall** [comment]
Did you rebase already?  If you haven't container base tests will fail against the new images because the Kafka configuration will be wrong.

**Comment by SamBarker** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=kroxylicious_kroxylicious-junit5-extension&pullRequest=423) **Quality Gate failed**  
> Failed conditions  
>  [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=kroxylicious_kroxylicious-junit5-extension&pullRequest=423&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)  
>  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=kroxylicious_kroxylicious-junit5-extension&pullRequest=423&metric=new_coverage&view=list) (required ≥ 80%)  
>   

Errr I wrote tests. What's happening to coverage??? A question for Monday

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/FloatingTagPullPolicy.java [hunk 11]
```diff
@@ -0,0 +1,54 @@
...
+
+import org.testcontainers.images.AbstractImagePullPolicy;
+import org.testcontainers.images.ImageData;
+import org.testcontainers.images.ImagePullPolicy;
+import org.testcontainers.images.PullPolicy;
+import org.testcontainers.utility.DockerImageName;
+
+import io.kroxylicious.testing.kafka.common.Version;
+
+public class FloatingTagPullPolicy extends AbstractImagePullPolicy implements ImagePullPolicy {
```
Comment (k-wall) [inline impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/FloatingTagPullPolicy.java:20]: Why not make this a KroxyliciousPullPolicy that knows about the special rules for latest etc and otherwise just falls back to PullPolicy.defaultPolicy() for all other tags.  That way TestcontainerKafkaCluster can just use the policy unconditionally.

Comment (SamBarker) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/FloatingTagPullPolicy.java:20]: Not sure I follow. I think this could be applied unconditionally, it's not currently however.

Extending the abstract means we are only invoked if there is already an image in the cache.

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java [hunk 12]
```diff
@@ -852,4 +900,6 @@ private String buildScramUsersEnvVar() {
                 .collect(Collectors.joining(";"));
     }
 
+    record PullPolicyForImage(DockerImageName dockerImageName, ImagePullPolicy pullPolicy) {
```
Comment (k-wall) [inline impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java:903]: Dead code.

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/FloatingTagPullPolicy.java (hunk 11 above)
Comment (k-wall) [reply impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/FloatingTagPullPolicy.java:20]: > I think this could be applied unconditionally, it's not currently however.

that's what I was trying to say.

File: impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/FloatingTagPullPolicy.java [hunk 13]
```diff
@@ -0,0 +1,57 @@
...
```
Comment (k-wall) [inline impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/FloatingTagPullPolicy.java:20]: nit: make package private

**Review by k-wall — APPROVED** [review]
couple of nits but otherwise lgtm
