### PR TITLE
Fix #378: Fix unsafe publication to HashMap used to track running kafka brokers.

### LINKED ISSUE #378: Test failure seemingly from Kafka during release workflow ExpositionIT#canConfigureLowestBrokerIdWithPortPerBroker
**Describe the bug**

We saw a test failure during a release workflow.  It appeared to be from Kafka itself, rather than Kroxylicious.
I haven't seen this issue before.  I haven't investigated further.

```
2024-08-20T12:49:04.7868051Z [ERROR] io.kroxylicious.proxy.ExpositionIT.canConfigureLowestBrokerIdWithPortPerBroker(KafkaCluster, Admin) -- Time elapsed: 1.058 s <<< ERROR!
2024-08-20T12:49:04.7870518Z java.lang.IllegalArgumentException: Broker node 0 is not a member of the cluster.
2024-08-20T12:49:04.7872622Z 	at io.kroxylicious.testing.kafka.invm.InVMKafkaCluster.removeBroker(InVMKafkaCluster.java:313)
2024-08-20T12:49:04.7875008Z 	at io.kroxylicious.proxy.ExpositionIT.canConfigureLowestBrokerIdWithPortPerBroker(ExpositionIT.java:514)
2024-08-20T12:49:04.7877107Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-08-20T12:49:04.7878741Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
2024-08-20T12:49:04.7880248Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**To Reproduce**
1. Configure kroxylicious like this ...
2. Run command '....'
3. See error

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

[logs_27378716046.zip](https://github.com/user-attachments/files/16676133/logs_27378716046.zip)

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

Fix unsafe publication to HashMap used to track running kafka brokers.

why: Kafka servers are started in parallel (by design) but the data structure used to track the servers was not thread safe. This probably accounts for the accounting error spotted in #378.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

File: impl/src/main/java/io/kroxylicious/testing/kafka/invm/InVMKafkaCluster.java [hunk 1]
```diff
@@ -75,9 +75,8 @@ public class InVMKafkaCluster implements KafkaCluster, KafkaClusterConfig.KafkaE
 
     /**
      * Map of kafka <code>node.id</code> to {@link Server}.
-     * Protected by lock of {@link InVMKafkaCluster itself.}
      */
-    private final Map<Integer, Server> servers = new HashMap<>();
+    private final Map<Integer, Server> servers = new ConcurrentHashMap<>();
```
Comment (SamBarker) [inline impl/src/main/java/io/kroxylicious/testing/kafka/invm/InVMKafkaCluster.java:79]: Should we make the LHS `ConcurrentMap` instead of `Map`?

**Review by SamBarker — APPROVED** [review]

**Comment by SamBarker** [comment]
Sonar appears to be dazed and confused.
